version: '2.4'
services:
  viki:
    restart: always
    build:
      context: ./viki
    env_file: .env
    ports:
      - 8001:8001
    volumes:
      - ./viki:/usr/src/app
    links:
      - db
    working_dir: /usr/src/app
    command: python3.6 demon.py

  viewer:
    restart: always
    build:
      context: ./viewer
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - ./viki/config.py:/usr/scr/app/config.py
      - ./viewer:/usr/src/app
    links:
      - db
    working_dir: /usr/src/app
    command: python3.6 app.py

#  nginx:
#    restart: always
#    image: nginx
#    ports:
#      - 60080:80
#    volumes:
#      - ./nginx/no-ssl:/etc/nginx/conf.d/default.conf
#    volumes_from:
#      - viewer
#    links:
#      - viewer

  db:
    restart: always
    image: postgres:latest
    volumes_from:
      - data
    expose:
      - 5432

  data:
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql/data
